### PR TITLE
V2 - only some tools

### PR DESCRIPTION
**Pull request by palmenhq**
Since it's not used anywhere anymore lets just centralize the utils.

### CODE REVIEW

**Review by styrelius — APPROVED** [review]
The code looks good to me but I don't really get it 😳  This is _not_ used? But it's still connected to allowing Lokalise translations in Embark? Sorry, just confused about what this is haha! 😅 But if it's too complicated to explain in text here we can take it some other time

**Comment by palmenhq** [comment]
@styrelius We only used this in the web onboarding i believe, and we've replaced all the stuff we used from here now :)

**Comment by palmenhq** [comment]
...so i figured let's just place some common util stuff we need across the repos in this repo

**Review by gustaveen — APPROVED** [review]
Nice! 🧹

**Pull request merged**
